nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  rhino.fi:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_ACCESS_TOKEN-}"
    npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
